apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-users
  template:
    metadata:
      labels:
        app: app-users
    spec:
      containers:
      - name: users
        image: rchauhan9102/kub-demo-users:1
