apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
      - name: users
        image: rchauhan9102/kub-demo-users:1
        env:
          - name: AUTH_ADDRESS
            value: localhost
      # - name: auth
      #   image: rchauhan9102/kub-demo-auth:1
