apiVersion: v1
kind: PersistentVolume
metadata:
  name: host-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: FilesSystem
  accessed: 
    - ReadWriteOnce
  hostPath:
    path: /data/
    type: DirectoryOrCreate